# Generated by Django 6.0 on 2026-04-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="informesuso",
            name="reservasCanceladas",
            field=models.IntegerField(default=0),
        ),
    ]
