# Generated by Django 6.0 on 2026-01-16 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LecturaMatricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.CharField(max_length=15)),
                ("fechaHora", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SALIDA", "Salida")],
                        max_length=10,
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("OK", "Correcto"),
                            ("SIN_RESERVA", "Sin reserva"),
                            ("DENEGADO", "Denegado"),
                            ("ERROR", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
