# Generated by Django 6.0 on 2026-01-16 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lecturas", "0001_initial"),
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturamatricula",
            name="reserva",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reservas.reserva",
            ),
        ),
    ]
