# Generated by Django 6.0 on 2026-01-16 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plazas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaInicio", models.DateTimeField()),
                ("fechaFinal", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RESERVADA", "Reservada"),
                            ("OCUPADA", "Ocupada en plaza"),
                            ("FINALIZADA", "Finalizada"),
                            ("CANCELADA", "Cancelada"),
                            ("NO_SHOW", "No se presentó"),
                        ],
                        default="RESERVADA",
                        max_length=20,
                    ),
                ),
                (
                    "plaza",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas",
                        to="plazas.plaza",
                    ),
                ),
            ],
        ),
    ]
