# Generated by Django 6.0 on 2026-04-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente de asignación"),
                    ("ASIGNADA", "Asignada"),
                    ("NO_ASIGNADA", "No asignada"),
                    ("OCUPADA", "Ocupada en plaza"),
                    ("FINALIZADA", "Finalizada"),
                    ("CANCELADA", "Cancelada"),
                    ("NO_SHOW", "No se presentó"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
