# Generated by Django 6.0 on 2026-04-27 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0004_alter_reserva_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="fechaFinal",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="fechaInicio",
        ),
        migrations.AddField(
            model_name="reserva",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
