# Generated by Django 6.0 on 2026-01-16 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.IntegerField()),
                ("numeroPlazas", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Plaza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("disponible", models.BooleanField(default=True)),
                (
                    "planta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plazas.planta"
                    ),
                ),
            ],
            options={
                "unique_together": {("numero", "planta")},
            },
        ),
    ]
